name: Build & Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # The build context is the root of your repository
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-list-nodejs:latest # Tag your image as your_docker_username/your_repo_name:latest
          # Optional: You might need to pass the DB_CONNECTION variable during the build if
          # your application somehow consumes it during npm install or pre-build steps.
          # However, it's generally best to pass runtime secrets at 'docker run' time.
          # If your app needs it *only* at runtime, you don't need this.
          # build-args: |
          #   DB_CONNECTION=${{ secrets.DB_CONNECTION }} # You would need to add DB_CONNECTION as a GitHub Secret if you use this

      - name: Verify Image Push (Optional)
        run: |
          echo "Docker image ${{ secrets.DOCKER_USERNAME }}/todo-list-nodejs:latest pushed successfully."
          # You could add 'docker pull' here to verify, but for simple CI, push success is usually enough.